#!/bin/bash
if [ ! -d build ]; then
	mkdir build
fi
if [ ! -d shared ]; then
	mkdir shared
fi

docker run --rm -it -v $(pwd)/shared:/shared -w /build --cap-add=SYS_ADMIN --security-opt apparmor:unconfined freddierice/qubes-builder 
